name: cc-tool
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Programming tool for TI CC series MCU
description: |
  This tool can drive CC-Debugger to erase, program, and verify MCU.

grade: stable

confinement: devmode

apps:
  run:
     command: cc-tool
     plugs: [raw-usb, home, network, network-bind]

parts:
  my-part:
    # See 'snapcraft plugins'
    source: https://github.com/dashesy/cc-tool.git
    plugin: autotools
    stage-packages:
        - libusb-1.0-0-dev
        - libboost-filesystem-dev
        - libboost-system-dev
        - libboost-program-options-dev
        - libboost-regex-dev
        - pkg-config
